version: '3.1'
services:
  zabbix-mysql:
    image: mysql:5.6
    container_name: zabbix-mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: zabbix
    volumes:
      - /root/zabbix/mysql-data:/var/lib/mysql
    networks:
      testing_net:
        ipv4_address: 172.31.3.11

  zabbix-server:
    image: zabbix/zabbix-server-mysql:ubuntu-4.4.6
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: "zabbix-mysql"
      MYSQL_USER: root
      MYSQL_PASSWORD: zabbix
    ports:
      - '10051:10051'
    links:
      - zabbix-mysql
    depends_on:
      - zabbix-mysql
    networks:
      testing_net:
        ipv4_address: 172.31.3.12

  zabbix-web:
    image: zabbix/zabbix-web-apache-mysql:ubuntu-4.4.6
    container_name: zabbix-web
    environment:
      DB_SERVER_HOST: zabbix-mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: zabbix
      ZBX_SERVER_HOST: "zabbix-server"
      PHP_TZ: America/Sao_Paulo
    ports:
      - '80:80'
      - '443:443'
    links:
      - zabbix-mysql
      - zabbix-server
    depends_on:
      - zabbix-mysql
      - zabbix-server
    networks:
      testing_net:
        ipv4_address: 172.31.3.13
  zabbix-java:
    image: zabbix/zabbix-java-gateway:ubuntu-4.4.6
    container_name: zabbix-java
    links:
      - zabbix-server
    depends_on:
      - zabbix-server
    networks:
      testing_net:
        ipv4_address: 172.31.3.14

  zabbix-agent:
    image: zabbix/zabbix-agent:ubuntu-4.4.6
    container_name: zabbix-agent
    environment:
      ZBX_HOSTNAME: zabbix-agent
      ZBX_SERVER_HOST: zabbix-server
    ports:
      - '10050:10050'
    links:
      - zabbix-server
    depends_on:
      - zabbix-server
    networks:
      testing_net:
        ipv4_address: 172.31.3.15

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.31.0.0/16
